<template><view class="page"><xy-header title="会员账单" /><view class="wrap">
  <xy-state v-if="loading" type="loading" />
  <xy-state v-else-if="error" type="error" title="付款记录加载失败" :description="error" action-text="重新加载" @action="load" />
  <block v-else><view v-if="bills.length" class="overview"><view><text>会员付款记录</text><text>{{ bills.length }} 笔</text></view><xy-icon name="wallet" :size="46" color="#0B756E" :weight="1.7" /></view>
  <view class="bill-list"><view v-for="bill in bills" :key="bill.paymentNo" class="bill"><view class="bill-icon"><xy-icon name="card" :size="34" color="#0B756E" :weight="1.8" /></view><view class="bill-copy"><text>{{ types[bill.businessType] || '会员服务' }}</text><text>{{ channelLabel(bill.channel) }} · {{ formatTime(bill.paidTime || bill.createTime) }}</text><text>业务单 {{ bill.businessOrderNo || '—' }}</text><text>支付单 {{ bill.paymentNo }}</text></view><view class="bill-amount"><text>¥{{ bill.amount }}</text><text>{{ billStatus(bill) }}</text></view></view></view>
  <view v-if="!bills.length" class="empty"><view><xy-icon name="wallet" :size="60" color="#0B756E" :weight="1.5" /></view><text class="empty-title">暂无付款记录</text><text class="empty-note">会员开卡申请、历史付款与退款记录会显示在这里。</text></view></block>
</view></view></template>
<script>
import { appRequest, ensureMemberSession, showRequestError } from '../../utils/api'
export default { data(){return{bills:[],loading:true,error:'',types:{MEMBERSHIP:'会员开卡'},statusLabel:{PENDING:'待付款',SUCCESS:'付款成功',CLOSED:'已关闭',REFUNDING:'退款处理中',REFUNDED:'已退款'}}}, onShow(){this.load()}, methods:{ async load(){this.loading=true;this.error='';try{await ensureMemberSession();const records=await appRequest({url:'/app/bills'});this.bills=(Array.isArray(records)?records:[]).filter((bill)=>bill.businessType==='MEMBERSHIP')}catch(error){this.error=(error&&error.message)||'网络连接失败'}finally{this.loading=false}}, formatTime(value){return value?String(value).replace('T',' ').slice(0,16):'--'}, channelLabel(channel){return{OFFLINE:'到店付款',WECHAT:'微信支付',DEMO:'演示记录'}[channel]||'付款记录'}, billStatus(bill){return bill.status==='PENDING'&&bill.channel==='OFFLINE'?'待门店确认':this.statusLabel[bill.status]||bill.status} } }
</script>
<style scoped>
.page{min-height:100vh;background:#edf5f3}.wrap{padding:26rpx}.overview{display:flex;align-items:center;justify-content:space-between;padding:28rpx;border-radius:28rpx;background:#dcefe9}.overview>view{display:flex;flex-direction:column;gap:7rpx}.overview text:first-child{color:#607873;font-size:21rpx}.overview text:last-child{font-size:31rpx;font-weight:750}.bill-list{margin-top:20rpx}.bill{display:flex;align-items:center;gap:16rpx;min-height:118rpx;padding:20rpx 0;border-bottom:1rpx solid #dce8e5}.bill-icon{display:flex;align-items:center;justify-content:center;width:64rpx;height:64rpx;border-radius:20rpx;background:#e0efeb}.bill-copy{display:flex;flex:1;flex-direction:column;gap:5rpx;min-width:0}.bill-copy text:first-child{font-size:25rpx;font-weight:700}.bill-copy text:nth-child(2){color:#748984;font-size:20rpx}.bill-copy text:nth-child(n+3){overflow:hidden;color:#98a7a4;font-size:18rpx;text-overflow:ellipsis;white-space:nowrap}.bill-amount{display:flex;flex-direction:column;align-items:flex-end;gap:7rpx}.bill-amount text:first-child{font-size:27rpx;font-weight:750}.bill-amount text:last-child{color:#0b756e;font-size:19rpx}.empty{display:flex;flex-direction:column;align-items:center;padding:118rpx 50rpx;text-align:center}.empty>view{display:flex;align-items:center;justify-content:center;width:108rpx;height:108rpx;border-radius:34rpx;background:#dcefe9}.empty-title{margin-top:25rpx;font-size:30rpx;font-weight:750}.empty-note{margin-top:12rpx;color:#748984;font-size:22rpx;line-height:1.6}
</style>
