<template><view class="page"><xy-header title="消费账单" /><view class="wrap">
  <view v-if="bills.length" class="overview"><view><text>账单记录</text><text>{{ bills.length }} 笔</text></view><xy-icon name="wallet" :size="46" color="#0B756E" :weight="1.7" /></view>
  <view class="bill-list"><view v-for="bill in bills" :key="bill.paymentNo" class="bill"><view class="bill-icon"><xy-icon :name="bill.businessType==='MEMBERSHIP'?'card':'bag'" :size="34" color="#0B756E" :weight="1.8" /></view><view class="bill-copy"><text>{{ types[bill.businessType] || bill.businessType }}</text><text>{{ formatTime(bill.paidTime || bill.createTime) }}</text><text>{{ bill.paymentNo }}</text></view><view class="bill-amount"><text>¥{{ bill.amount }}</text><text>{{ statusLabel[bill.status] || bill.status }}</text></view></view></view>
  <view v-if="!bills.length" class="empty"><view><xy-icon name="wallet" :size="60" color="#0B756E" :weight="1.5" /></view><text class="empty-title">暂无消费账单</text><text class="empty-note">会员开卡和商城支付记录会显示在这里。</text></view>
</view></view></template>
<script>
import { appRequest, ensureMemberSession, showRequestError } from '../../utils/api'
export default { data(){return{bills:[],types:{ORDER:'商城订单',MEMBERSHIP:'会员开卡'},statusLabel:{PENDING:'待支付',SUCCESS:'支付成功',CLOSED:'已关闭',REFUNDED:'已退款'}}}, onShow(){this.load()}, methods:{ async load(){try{await ensureMemberSession();this.bills=await appRequest({url:'/app/bills'})}catch(error){showRequestError(error)}}, formatTime(value){return value?String(value).replace('T',' ').slice(0,16):'--'} } }
</script>
<style scoped>
.page{min-height:100vh;background:#edf5f3}.wrap{padding:26rpx}.overview{display:flex;align-items:center;justify-content:space-between;padding:28rpx;border-radius:28rpx;background:#dcefe9}.overview>view{display:flex;flex-direction:column;gap:7rpx}.overview text:first-child{color:#607873;font-size:21rpx}.overview text:last-child{font-size:31rpx;font-weight:750}.bill-list{margin-top:20rpx}.bill{display:flex;align-items:center;gap:16rpx;min-height:118rpx;padding:20rpx 0;border-bottom:1rpx solid #dce8e5}.bill-icon{display:flex;align-items:center;justify-content:center;width:64rpx;height:64rpx;border-radius:20rpx;background:#e0efeb}.bill-copy{display:flex;flex:1;flex-direction:column;gap:5rpx;min-width:0}.bill-copy text:first-child{font-size:25rpx;font-weight:700}.bill-copy text:nth-child(2){color:#748984;font-size:20rpx}.bill-copy text:last-child{overflow:hidden;color:#98a7a4;font-size:18rpx;text-overflow:ellipsis;white-space:nowrap}.bill-amount{display:flex;flex-direction:column;align-items:flex-end;gap:7rpx}.bill-amount text:first-child{font-size:27rpx;font-weight:750}.bill-amount text:last-child{color:#0b756e;font-size:19rpx}.empty{display:flex;flex-direction:column;align-items:center;padding:118rpx 50rpx;text-align:center}.empty>view{display:flex;align-items:center;justify-content:center;width:108rpx;height:108rpx;border-radius:34rpx;background:#dcefe9}.empty-title{margin-top:25rpx;font-size:30rpx;font-weight:750}.empty-note{margin-top:12rpx;color:#748984;font-size:22rpx;line-height:1.6}
</style>
