<template><view class="page"><xy-header title="邀请好友" /><view class="wrap">
  <view class="invite-card"><view class="mark"><xy-icon name="gift" :size="54" color="#F5DCA7" :weight="1.7" /></view><text class="headline">一起解锁轻松钓虾时光</text><text class="note">把邀请码分享给好友，邀请他加入钓虾生活馆。</text><view class="code-box"><text>我的邀请码</text><text class="code">{{ inviteCode || '------' }}</text></view></view>
  <view class="actions"><button class="copy" @click="copy"><xy-icon name="doc" :size="34" color="#0B756E" :weight="1.8" />复制邀请码</button><button class="share" open-type="share"><xy-icon name="share" :size="34" color="#F3FCF9" :weight="1.8" />分享给好友</button></view>
  <view class="tip"><xy-icon name="info" :size="32" color="#607873" :weight="1.7" /><text>好友从分享卡片进入后，可以在会员资料中看到自己的专属邀请码。</text></view>
</view></view></template>
<script>
import { appRequest, ensureMemberSession, showRequestError } from '../../utils/api'
export default { data(){return{inviteCode:''}}, onLoad(){this.load()}, onShareAppMessage(){return{title:`邀请你加入钓虾生活馆，邀请码 ${this.inviteCode}`,path:`/pages/login/login?inviteCode=${encodeURIComponent(this.inviteCode || '')}`}}, methods:{ async load(){try{await ensureMemberSession();this.inviteCode=(await appRequest({url:'/app/me'})).inviteCode}catch(error){showRequestError(error)}}, copy(){if(this.inviteCode)uni.setClipboardData({data:this.inviteCode})} } }
</script>
<style scoped>
.page{min-height:100vh;background:#edf5f3}.wrap{padding:28rpx}.invite-card{position:relative;overflow:hidden;display:flex;flex-direction:column;align-items:center;padding:54rpx 36rpx;border-radius:36rpx;background:#164b46;color:#f1faf7;text-align:center;box-shadow:0 20rpx 48rpx rgba(16,67,62,.2)}.invite-card::after{content:'';position:absolute;right:-90rpx;top:-100rpx;width:320rpx;height:320rpx;border:2rpx solid rgba(245,220,167,.14);border-radius:50%}.mark{position:relative;z-index:1;display:flex;align-items:center;justify-content:center;width:96rpx;height:96rpx;border-radius:30rpx;background:rgba(245,220,167,.12)}.headline{position:relative;z-index:1;margin-top:25rpx;font-size:35rpx;font-weight:780}.note{position:relative;z-index:1;max-width:25em;margin-top:12rpx;color:#bcd9d3;font-size:22rpx;line-height:1.6}.code-box{position:relative;z-index:1;width:100%;margin-top:36rpx;padding:24rpx;border:1rpx solid rgba(225,245,239,.18);border-radius:26rpx;background:rgba(237,250,246,.08)}.code-box>text:first-child{display:block;color:#a9cbc4;font-size:20rpx}.code{display:block;margin-top:8rpx;color:#f5dca7;font-size:54rpx;font-weight:800;letter-spacing:10rpx}.actions{display:grid;grid-template-columns:1fr 1fr;gap:16rpx;margin-top:24rpx}.actions button{display:flex;align-items:center;justify-content:center;gap:9rpx;height:90rpx;border-radius:26rpx;font-size:24rpx;font-weight:700}.copy{border:1rpx solid #cfe0dc;background:#f8fcfa;color:#0b756e}.share{background:#0b756e;color:#f3fcf9}.tip{display:flex;align-items:flex-start;gap:14rpx;margin-top:26rpx;padding:22rpx;border-radius:24rpx;background:#e2eeeb;color:#607873;font-size:21rpx;line-height:1.6}
</style>
