<template><view class="page"><xy-header title="我的预约" /><view class="wrap">
  <view v-if="records.length" class="summary"><text>共 {{ records.length }} 条预约记录</text><text>点击查看签到码与门店信息</text></view>
  <view v-for="item in records" :key="item.reservationNo" class="record" @click="detail(item)">
    <view class="record-top"><view class="date"><text>{{ shortDate(item.reservationDate) }}</text><text>{{ item.startTime }}–{{ item.endTime }}</text></view><text class="status" :class="statusClass(item.status)">{{ labels[item.status] || item.status }}</text></view>
    <view class="place"><view class="place-icon"><xy-icon name="seat" :size="36" color="#0B756E" :weight="1.8" /></view><view><text>{{ item.storeName }}</text><text>{{ item.zoneName }} {{ item.seatCode }}</text></view><xy-icon name="chevron-right" :size="30" color="#91A39F" :weight="1.7" /></view>
  </view>
  <view v-if="!records.length" class="empty"><view class="empty-icon"><xy-icon name="calendar" :size="60" color="#0B756E" :weight="1.5" /></view><text class="empty-title">还没有预约</text><text class="empty-note">选择合适的场次和座位，提前安排一次轻松钓虾。</text><button @click="reserve">去预约座位</button>
    <view class="steps"><view><xy-icon name="clock" :size="29" color="#0b756e"/><text>选择时段</text></view><view><xy-icon name="seat" :size="29" color="#0b756e"/><text>挑选座位</text></view><view><xy-icon name="check" :size="29" color="#0b756e"/><text>确认预约</text></view></view>
  </view>
</view></view></template>
<script>
import { appRequest, ensureMemberSession, showRequestError } from '../../utils/api'
export default { data(){return{records:[],labels:{BOOKED:'待到场',CHECKED_IN:'已签到',CANCELED:'已取消',NO_SHOW:'已过期'}}}, onShow(){this.load()}, methods:{ async load(){try{await ensureMemberSession();this.records=await appRequest({url:'/app/reservations'})}catch(error){showRequestError(error)}}, shortDate(date){if(!date)return'--';const p=String(date).split('-');return`${Number(p[1])}月${Number(p[2])}日`}, statusClass(status){return status==='BOOKED'?'booked':status==='CHECKED_IN'?'checked':'muted'}, detail(item){uni.navigateTo({url:`/pages/reserve/detail?reservationNo=${item.reservationNo}`})}, reserve(){uni.reLaunch({url:'/pages/reserve/reserve'})} } }
</script>
<style scoped>
.page{min-height:100vh;background:#edf5f3}.wrap{padding:26rpx}.summary{display:flex;justify-content:space-between;margin:2rpx 4rpx 18rpx;color:#748984;font-size:21rpx}.record{margin-bottom:18rpx;padding:26rpx;border:1rpx solid #dbe8e4;border-radius:28rpx;background:#f8fcfa}.record-top{display:flex;align-items:flex-start;justify-content:space-between;padding-bottom:22rpx;border-bottom:1rpx solid #e1ebe8}.date{display:flex;flex-direction:column;gap:8rpx}.date text:first-child{font-size:29rpx;font-weight:750}.date text:last-child{color:#5e746f;font-size:23rpx}.status{padding:7rpx 13rpx;border-radius:16rpx;font-size:20rpx;font-weight:650}.status.booked{background:#dcefe9;color:#0b756e}.status.checked{background:#e0edf2;color:#32778c}.status.muted{background:#e7ecea;color:#7b8d89}.place{display:flex;align-items:center;gap:16rpx;padding-top:20rpx}.place-icon{display:flex;align-items:center;justify-content:center;width:62rpx;height:62rpx;border-radius:19rpx;background:#e0efeb}.place>view:nth-child(2){display:flex;flex:1;flex-direction:column;gap:5rpx}.place>view:nth-child(2) text:first-child{font-size:25rpx;font-weight:700}.place>view:nth-child(2) text:last-child{color:#7a8d88;font-size:21rpx}.empty{display:flex;flex-direction:column;align-items:center;padding:96rpx 30rpx 40rpx;text-align:center}.empty-icon{display:flex;align-items:center;justify-content:center;width:108rpx;height:108rpx;border-radius:34rpx;background:#dcefe9}.empty-title{margin-top:25rpx;font-size:30rpx;font-weight:750}.empty-note{max-width:25em;margin-top:12rpx;color:#748984;font-size:22rpx;line-height:1.6}.empty button{height:82rpx;margin-top:28rpx;padding:0 36rpx;border-radius:24rpx;background:#0b756e;color:#f3fcf9;font-size:25rpx;font-weight:700}.empty .steps{display:flex;width:100%;margin-top:66rpx;padding:28rpx 14rpx;border-radius:26rpx;background:#f8fcfa}.steps>view{display:flex;flex:1;flex-direction:column;align-items:center;gap:10rpx;color:#667b76;font-size:20rpx}.steps>view+view{border-left:1rpx solid #dce7e4}
</style>
